[package]
name = "playht_rs"
version = "0.1.0"
description = "A library for interacting with Play.HT API"
authors = ["milosgajdos <milosthegajdos@gmail.com>"]
license = "Apache 2.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/milosgajdos/playht_rs"
keywords = ["playht", "play.ht", "tts", "text-to-speech", "voice-clone", "ai"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
